### ISSUE TITLE
Is there a setup.py somewhere?  can't seem to get this installed/  

### ISSUE THREAD

**Issue by bromrector** [rsvp/fecon235#4]
### Description of specific issue
Whenever I try to import any of the modules (python 3.5 anaconda, linux mint), I get "SystemError", parent module 'not loaded, cannot perform relative import

- [ ] Bug
- [ ] Enhancement

### Steps which reproduce or enhance behavior

1. 
2. 

```
Optional: Markdown to include images...
![Screenshot for demonstration](url)
```

### Additional helpful details for bugs

- [ ] Problem started recently, but not in older versions
- [ ] Problem happens with all files, not only some files
- [ ] Problem can be reliably reproduced
- [ ] Problem happens randomly

- **fecon235 version:** 
- **pandas version:** 
- **Python version:** 
- **Operating system:** 

ATTN mention: @rsvp

**Comment by rsvp** [comment]
Installing fecon235 is simply a matter of placing the repo's top directory in the scope of your PYTHONPATH.

@bromrector Was the introduction satisfactory to resolve this issue? If not, could you kindly help out by clarifying the documentation? Thanks very much!
